language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - pip install pylint pep8 pep257 flake8 coverage

script:
  - ./.unit-tests.sh

# vim:ai:et:sw=2:ts=2:sts=2:tw=0:fenc=utf-8
