language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - pip install pylint pyflakes pep8 pep257

script:
  - ./.test-cmdwrapper.sh

# vim:ai:et:sw=2:ts=2:sts=2:tw=0:fenc=utf-8
