language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  # Travis already include pytest, need to upgrade it when unpinned
  - if [[ "${DEPS_RESOLVE}" == "UNPINNED" ]]; then pip install -U pytest; fi
  - pip install -r requirements.txt
  - pip install -q coveralls --use-wheel

script:
  - py.test --cov=cmdwrapper --pep8 -v

after_success:
  - coveralls

# vim:ai:et:sw=2:ts=2:sts=2:tw=0:fenc=utf-8
